CREATE TABLE IF NOT EXISTS COMPANY(
    ID INT SERIAL PRIMARY KEY,
    NAME VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS CAR(
    ID INT SERIAL PRIMARY KEY,
    NAME VARCHAR UNIQUE NOT NULL,
    COMPANY_ID INT NOT NULL,
    CONSTRAINT fk_company_id FOREIGN KEY(COMPANY_ID)
    REFERENCES COMPANY(ID)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS CUSTOMER(
    ID INT SERIAL PRIMARY KEY,
    NAME VARCHAR UNIQUE NOT NULL,
    RENTED_CAR_ID INT,
    CONSTRAINT fk_car_id FOREIGN KEY(RENTED_CAR_ID)
    REFERENCES CAR(ID)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
);
